language: python
sudo: false
addons:
    apt:
        packages:
          - enchant

python:
    - "2.7"
    - "3.4"

# command to install dependencies
install:
    - pip install .
    - pip install -r docs/requirements.txt

# command to run tests
script:
    - 'sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html'
    - 'sphinx-build -b spelling -d doc/_build/doctrees docs _build/html'
    - 'sphinx-build -b linkcheck -d docs/_build/doctrees docs docs/_build/html'
